apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 083828157205.dkr.ecr.us-east-1.amazonaws.com/frontendmovie:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_MOVIE_API_URL
              value: "http://backend-service:5000" 			
