---
name: Backend CI Pipeline
on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**
  workflow_dispatch: null
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Cache Python dependencies with Pipenv
        uses: actions/cache@v2
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-deps-${{ hashFiles('backend/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-deps-		  
      - name: Install dependencies with pipenv
        run: |
          cd backend 
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run linting with flake8
        id: lint
        run: cd backend &&  pipenv run flake8 --max-line-length=120
        continue-on-error: false
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Cache Python dependencies with Pipenv
        uses: actions/cache@v2
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-deps-${{ hashFiles('backend/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-deps-		  
      - name: Install dependencies with pipenv
        run: |
          cd backend 
          python -m pip install --upgrade pip
          pip install pipenv 
          pipenv install --dev
      - name: Run tests with pytest
        run: cd backend && pipenv run pytest --maxfail=1 --disable-warnings -q
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  
