name: Backend CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**' 
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
	
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Adjust according to your project’s required Node version

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run ESLint (TypeScript + React)
        run: |
          cd backend
          npm run lint  # Assuming 'lint' is the npm script that runs ESLint, configured for TypeScript and React
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Update with the correct Node version if using Node.js

      - name: Install Dependencies
        run: cd backend && npm ci

      - name: Run Unit Tests
        run: cd backend && npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build backend Application
        run: npm run build 
		
      - name: Build Docker image
        run: |
          cd backend
          docker build -t backend-app -f backend/Dockerfile . 