---
name: Frontend CI/CD Pipeline
on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
  workflow_dispatch: null
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: cd frontend && npm ci
      - name: Run Unit Tests
        run: cd frontend && npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: cd frontend && npm ci
      - name: Run Unit Tests
        run: cd frontend/src/components/__tests__ && npm test
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Fix permissions for react-scripts
        run: |
          cd frontend
          chmod +x node_modules/.bin/react-scripts		
      - name: Build Frontend Application
        run: cd frontend && npm run build
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_Session_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: Build Docker image
        run: >
          cd frontend docker build -t ${{ secrets.REGISTRY_USERNAME }}:${{ github.sha
          }} -f Dockerfile .
      - name: Push Docker image to AWS ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }}
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}:latest		
