---
name: Frontend CI/CD Pipeline
on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
  workflow_dispatch: null
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: cd frontend && npm ci
      - name: Run Unit Tests
        run: cd frontend && npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: cd frontend && npm ci
      - name: Run Unit Tests
        run: cd frontend && npm test
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Frontend Application
        run: cd frontend && npm run build
      - name: Build Docker image
        run: |
          cd frontend
          docker build -t frontend-app -f frontend/Dockerfile .		
